spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_master
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
